"""forecasts, data sources, archive (milestone 2)

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-22 23:01:54.166704
"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None

# Sources de données : licence d'usage (open / non_commercial / contract) et coût (free / paid).
# Open-Meteo : licence et coût réels dépendent du mode configuré (public / api_key / self_hosted),
# voir app.forecasts.governance.
SOURCES = [
    {"code": "nomads", "name": "NOAA NOMADS (grib filter)", "usage_licence": "open", "cost": "free",
     "enabled": True, "implemented": True, "terms_url": "https://www.weather.gov/disclaimer",
     "notes": "Server-side subsetting; fair-use limit ~120 requests/min; ~10 days kept."},
    {"code": "aws", "name": "AWS Open Data (NOAA GFS/GEFS, ECMWF open data mirror)", "usage_licence": "open",
     "cost": "free", "enabled": True, "implemented": True,
     "terms_url": "https://registry.opendata.aws/", "notes": "Global fields via byte ranges; multi-year archives."},
    {"code": "ecmwf", "name": "ECMWF open data (data.ecmwf.int)", "usage_licence": "open", "cost": "free",
     "enabled": True, "implemented": True, "terms_url": "https://www.ecmwf.int/en/forecasts/datasets/open-data",
     "notes": "CC-BY 4.0; a few days kept."},
    {"code": "dwd", "name": "DWD opendata (ICON, ICON-EU)", "usage_licence": "open", "cost": "free",
     "enabled": True, "implemented": True, "terms_url": "https://www.dwd.de/EN/service/copyright/copyright_node.html",
     "notes": "~24 h kept: automatic archiving required for history."},
    {"code": "open_meteo", "name": "Open-Meteo", "usage_licence": "non_commercial", "cost": "free",
     "enabled": True, "implemented": True, "terms_url": "https://open-meteo.com/en/terms",
     "notes": "Point extraction; public API non-commercial only."},
    {"code": "ecmwf_hres_01", "name": "ECMWF IFS HRES 0.1° (real-time catalogue)", "usage_licence": "contract",
     "cost": "paid", "enabled": False, "implemented": False,
     "terms_url": "https://www.ecmwf.int/en/forecasts/accessing-forecasts",
     "notes": "Placeholder: not implemented; requires an ECMWF service agreement."},
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('usage_licence', sa.String(length=16), nullable=False),
    sa.Column('cost', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('implemented', sa.Boolean(), nullable=False),
    sa.Column('terms_url', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('nwp_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_code', sa.String(length=32), nullable=False),
    sa.Column('init_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('first_retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_code', 'init_time', 'source')
    )
    op.create_index(op.f('ix_nwp_run_init_time'), 'nwp_run', ['init_time'], unique=False)
    op.create_index(op.f('ix_nwp_run_model_code'), 'nwp_run', ['model_code'], unique=False)
    op.create_table('forecast_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task_log.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_job_created_at'), 'forecast_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_forecast_job_project_id'), 'forecast_job', ['project_id'], unique=False)
    op.create_index(op.f('ix_forecast_job_site_id'), 'forecast_job', ['site_id'], unique=False)
    op.create_table('forecast_extract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('model_code', sa.String(length=32), nullable=False),
    sa.Column('nwp_run_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('grid_point_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('n_members', sa.Integer(), nullable=False),
    sa.Column('n_times', sa.Integer(), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('missing_variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('estimate', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['forecast_job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nwp_run_id'], ['nwp_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_extract_job_id'), 'forecast_extract', ['job_id'], unique=False)
    op.add_column('project', sa.Column('archive_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('project', sa.Column('archive_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    op.add_column('project', sa.Column('archive_max_lead_h', sa.Integer(), server_default='168', nullable=False))
    # ### end Alembic commands ###

    data_source = sa.table(
        "data_source",
        sa.column("code", sa.String), sa.column("name", sa.String), sa.column("usage_licence", sa.String),
        sa.column("cost", sa.String), sa.column("enabled", sa.Boolean), sa.column("implemented", sa.Boolean),
        sa.column("terms_url", sa.String), sa.column("notes", sa.Text),
    )
    op.bulk_insert(data_source, SOURCES)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'archive_max_lead_h')
    op.drop_column('project', 'archive_models')
    op.drop_column('project', 'archive_enabled')
    op.drop_index(op.f('ix_forecast_extract_job_id'), table_name='forecast_extract')
    op.drop_table('forecast_extract')
    op.drop_index(op.f('ix_forecast_job_site_id'), table_name='forecast_job')
    op.drop_index(op.f('ix_forecast_job_project_id'), table_name='forecast_job')
    op.drop_index(op.f('ix_forecast_job_created_at'), table_name='forecast_job')
    op.drop_table('forecast_job')
    op.drop_index(op.f('ix_nwp_run_model_code'), table_name='nwp_run')
    op.drop_index(op.f('ix_nwp_run_init_time'), table_name='nwp_run')
    op.drop_table('nwp_run')
    op.drop_table('data_source')
    # ### end Alembic commands ###
