"""farm, turbines, mast, terrain (milestone 3)

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-22 23:29:05.465213
"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('met_mast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('input_crs', sa.String(length=32), nullable=False),
    sa.Column('input_x', sa.Float(), nullable=True),
    sa.Column('input_y', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_met_mast_geom', 'met_mast', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_met_mast_project_id'), 'met_mast', ['project_id'], unique=False)
    op.create_table('terrain_layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('crs', sa.String(length=64), nullable=False),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('z0_table', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terrain_layer_project_id'), 'terrain_layer', ['project_id'], unique=False)
    op.create_table('turbine_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('rotor_d_m', sa.Float(), nullable=False),
    sa.Column('rated_kw', sa.Float(), nullable=False),
    sa.Column('hub_heights_m', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rho_ref', sa.Float(), nullable=False),
    sa.Column('cut_in_ms', sa.Float(), nullable=False),
    sa.Column('cut_out_ms', sa.Float(), nullable=False),
    sa.Column('restart_ms', sa.Float(), nullable=True),
    sa.Column('power_curve', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('density_curves', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('temp_derating', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('source_filename', sa.String(length=300), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_turbine_type_project_id'), 'turbine_type', ['project_id'], unique=False)
    op.create_table('wind_farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_neighbour', sa.Boolean(), nullable=False),
    sa.Column('layout_filename', sa.String(length=300), nullable=False),
    sa.Column('layout_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wind_farm_project_id'), 'wind_farm', ['project_id'], unique=False)
    op.create_table('mast_dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mast_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('format', sa.String(length=32), nullable=False),
    sa.Column('mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('time_reference', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('file_uri', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('t_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('t_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('n_records', sa.Integer(), nullable=False),
    sa.Column('qc_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mast_id'], ['met_mast.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mast_dataset_mast_id'), 'mast_dataset', ['mast_id'], unique=False)
    op.create_table('mast_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mast_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('boom_dir_deg', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['mast_id'], ['met_mast.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mast_id', 'code')
    )
    op.create_index(op.f('ix_mast_sensor_mast_id'), 'mast_sensor', ['mast_id'], unique=False)
    op.create_table('turbine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('input_crs', sa.String(length=32), nullable=False),
    sa.Column('input_x', sa.Float(), nullable=True),
    sa.Column('input_y', sa.Float(), nullable=True),
    sa.Column('hub_height_m', sa.Float(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('dem_elevation_m', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['wind_farm.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['turbine_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'label')
    )
    op.create_index('idx_turbine_geom', 'turbine', ['geom'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_turbine_farm_id'), 'turbine', ['farm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turbine_farm_id'), table_name='turbine')
    op.drop_index('idx_turbine_geom', table_name='turbine', postgresql_using='gist')
    op.drop_table('turbine')
    op.drop_index(op.f('ix_mast_sensor_mast_id'), table_name='mast_sensor')
    op.drop_table('mast_sensor')
    op.drop_index(op.f('ix_mast_dataset_mast_id'), table_name='mast_dataset')
    op.drop_table('mast_dataset')
    op.drop_index(op.f('ix_wind_farm_project_id'), table_name='wind_farm')
    op.drop_table('wind_farm')
    op.drop_index(op.f('ix_turbine_type_project_id'), table_name='turbine_type')
    op.drop_table('turbine_type')
    op.drop_index(op.f('ix_terrain_layer_project_id'), table_name='terrain_layer')
    op.drop_table('terrain_layer')
    op.drop_index(op.f('ix_met_mast_project_id'), table_name='met_mast')
    op.drop_index('idx_met_mast_geom', table_name='met_mast', postgresql_using='gist')
    op.drop_table('met_mast')
    # ### end Alembic commands ###
